FROM heroku/heroku:20

RUN apt-get update -y; apt-get install default-jre default-jdk -y

# setup workspace
RUN rm -rf /tmp/workspace
RUN mkdir -p /tmp/workspace

# output dir is mounted
COPY build.sh /tmp/build.sh
RUN chmod +x /tmp/build.sh
CMD ["/tmp/build.sh", "/tmp/workspace", "/tmp/output", "/tmp/cache"]
