name: Build and upload JRuby runtime
run-name: "Build and upload JRuby ${{ inputs.jruby_version }}${{ inputs.dry_run && ' (dry run)' || '' }}"

on:
  workflow_dispatch:
    inputs:
      jruby_version:
          description: "The JRuby version to build, specified as X.Y.Z (i.e. 9.3.0.0)"
          type: string
          required: true
      dry_run:
          description: "Skip deploying to S3 (e.g. for testing)"
          type: boolean
          default: false
          required: false

permissions:
  contents: read

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"
  S3_BUCKET: "heroku-buildpack-ruby"

jobs:
  build-and-upload:
    strategy:
      fail-fast: false
      matrix:
        base_image: ["heroku-20", "heroku-22", "heroku-24"]
    env:
      BASE_IMAGE: ${{ matrix.base_image }}
    runs-on: pub-hk-ubuntu-22.04-xlarge
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print changelog
        run: bin/print_changelog ${{ inputs.jruby_version }} | tee $GITHUB_STEP_SUMMARY
      - name: Build Docker image
        run: bin/activate_docker $BASE_IMAGE
      - name: Build and package JRuby runtime
        run: bin/build_jruby $BASE_IMAGE ${{ inputs.jruby_version }}
      - name: Test JRuby runtime
        run: bin/print_summary $BASE_IMAGE ${{ inputs.jruby_version }} | tee $GITHUB_STEP_SUMMARY
      - name: Upload JRuby runtime archive to S3 dry run
        if: (inputs.dry_run)
        run: aws s3 sync ./builds "s3://${S3_BUCKET}" --dryrun
      - name: Upload JRuby runtime archive to S3 production
        if: (!inputs.dry_run)
        run: aws s3 sync ./builds "s3://${S3_BUCKET}"
